---
deployment:
  tasks:
    - export DEPLOYPATH=/home/qpimrbin/public_html/
    - /bin/cp /home/qpimrbin/repositories/qpi-money/index.html $DEPLOYPATH
    - /bin/cp /home/qpimrbin/repositories/qpi-money/style.css $DEPLOYPATH
